buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'maven-publish'
}

apply plugin: 'org.spongepowered.mixin'

group = 'com.ccr4ft3r'
version = System.getenv("GITHUB_HASH") ?: "${mc_version}-${mod_version}"

java {
    archivesBaseName = 'actions-of-stamina'
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.ADOPTIUM
    }
}

minecraft {
    mappings channel: 'official', version: mc_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'actions-of-stamina'

            mods {
                actionsofstamina {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                actionsofstamina {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'actions-of-stamina'

            mods {
                actionsofstamina {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'actionsofstamina', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                actionsofstamina {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, "actionsofstamina.refmap.json"
    config "actionsofstamina.mixins.json"
}

// Incluye recursos generados
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven { url "https://www.cursemaven.com" }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url = 'https://adoptopenjdk.jfrog.io/adoptopenjdk/maven/' }
    flatDir {
        dirs "$projectDir/libs"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"
    compileOnly("curse.maven:parcool-482378:${parcool_file_id}")
    implementation fg.deobf("curse.maven:create-328085:${create_file_id}")
    runtimeOnly fg.deobf("curse.maven:cloth-config-api-348521:${cloth_config_id}")
    runtimeOnly fg.deobf("curse.maven:configured-457570:${mod_configured_file_id}")
    implementation fg.deobf("com.elenai.feathers:greenfeathers:1.3.0")
    implementation fg.deobf("curse.maven:curios-309927:${curios_file_id}")
    implementation fg.deobf("curse.maven:angel-ring-333396:${mod_angel_ring_file_id}")
    implementation fg.deobf("curse.maven:architectury-419699:${architectury_file_id}")
    implementation fg.deobf("curse.maven:paragliders-289240:${mod_paragliders_file_id}")
    implementation fg.deobf("curse.maven:player-animator-658587:${player_animator_file_id}")
    implementation fg.deobf("curse.maven:elenai-dodge-442962:${elenai_dodge_file_id}")
    runtimeOnly fg.deobf("curse.maven:jei-238222:5101366")
    runtimeOnly fg.deobf("curse.maven:dummy-225738:5319203")
    runtimeOnly fg.deobf("curse.maven:moonlight-499980:5409387")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : "CCr4ft3r, Darkona",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            artifact jar
        }
    }
    repositories {
        maven {
            name = "GithubPackages"
            url = "https://maven.pkg.github.com/NewWind-Modpacks/actions-of-stamina"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
